### ISSUE TITLE
RAN stack suggestion

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#2]
## React . Apollo (GraphQL) . Next.js

I think this will get us up and running quickly enough so we're not getting bogged down with tooling 

https://github.com/Sly777/ran

Feedback appreciated @GreatScot and @afixoftrix

Vote with :+1:  or :-1:

**Comment by thomasmarr** [comment]
I've not looked at it in great detail yet, but am I right in thinking (i.e. from the description) that it's basically just boilerplate which brings our stack together so we don't have to faff about setting it up? Sounds good to me!

**Comment by spences10** [comment]
>I've not looked at it in great detail yet, but am I right in thinking (i.e. from the description) that it's basically just boilerplate which brings our stack together so we don't have to faff about setting it up? Sounds good to me!

### correct

I also haven't cloned and started using it, but it is a great start [on paper] which will [not entirely] sidestep all the tooling needed, there seems to be a lot of parts in there already

So we're just waiting to hear back from @afixoftrix 

I may be able to take a look at this tonight, I'll of had a few beers in me by then as I'm meeting a friend after work for a beer :rocket: :beers:

**Comment by spences10** [comment]
After reviewing this I think this stack is a bit overkill for what we want and we should try to concentrate on getting a small `next.js` app up and running.

**Comment by spences10** [comment]
I discussed this with the maintainer and this sounds like the best option for this so I will push the bootstrap to the `dev` branch later today

**Comment by spences10** [comment]
So, all agreed we're happy with this
