### ISSUE TITLE
Lessons learned from howtographql.com

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#25]
Use some of the things we learned from howtographql.com in HuddleHunt

Discussion thread on what we can add from HTG to HuddleHunt

Features I think we can get in there:

- [ ] Filtering Links with search query
...

**Comment by thomasmarr** [comment]
Still working my way through howtographql. On the authentication page just now. Not actually building Hackernews clone though - just reading.

**Comment by thomasmarr** [comment]
I think the timedifferencefordate would be a nice feature to make use of. I think we are going to need to enable users to communicate with each other one way or another, not sure of the format(s) yet but would be nice to put the "x hours ago" next to each message.

**Comment by spences10** [comment]
Ok, so looks like another user story for that then I guess.

Users can message each other?

**Comment by thomasmarr** [comment]
thought I already captured that somewhere. not the first priority really
but there will need to be some way to put users in touch with one another
surely? I suppose maybe not, if the huddle creator just specifies all the
details and none of them are up for discussion

**Comment by spences10** [comment]
Ok, well, I better check the issues 🙃 

This looks like it here: https://github.com/chungu-voyage-bears-team-16/huddlehunt/issues/16

Right?

**Comment by spences10** [comment]
Closing this, this we have enough features already in the backlog
