### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#29]
Hey @GreatScot 

Trying to run the master branch here and get the error here:

![image](https://user-images.githubusercontent.com/234708/31094227-5784b1ee-a7ac-11e7-96c0-04967eccf0a5.png)

Any ideas how to fix?

**Comment by thomasmarr** [comment]
Yeah you need to install the react-dropzone package from npm. I think I added it to packages.json but you need to update I guess.
