### ISSUE TITLE
Orientation w/ Next.js

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#4]
https://learnnextjs.com/

**Comment by spences10** [comment]
Check yourself off the list then we can close this :+1:

- [ ] @afixoftrix 
- [x] @GreatScot 
- [x] @spences10

**Comment by thomasmarr** [comment]
I'm only about halfway through (31 Jul 2017). Still trying to work through it piecemeal. Seems pretty straightforward though.

**Comment by spences10** [comment]
Yeah it does, and I'm guessing that the way the bootstrap does things is slightly different to how the demo works @GreatScot

**Comment by spences10** [comment]
closing this, we should all be familiar w/next.js now :ok_hand:
