### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#5]
User's to have the ability to log into the app

**Comment by spences10** [comment]
I need to get a hold of the Schema Definition Language from the maintainer so we can define our own from that.

@GreatScot mentioned searching for `.gql` in the source which is really helpful :+1: 

https://github.com/Sly777/ran/search?utf8=%E2%9C%93&q=.gql&type=

https://github.com/Sly777/ran/blob/0a071317df5fab6538a573d06566450dd75532b8/components/AuthFields/index.gql.js

**Comment by thomasmarr** [comment]
I'm still grappling with GraphQL and not sure how we build our own schema, how it interacts with the existing schema (in RAN) or whether we should just be 'extending' the existing schema? Next thing I'm planning to do is dig around a little on this - see if I can figure it out.
Let me know when you hear back from ran RAN maintainer.

**Comment by spences10** [comment]
Hey @GreatScot, I have put together a [cheatsheet](https://github.com/spences10/cheat-sheets/blob/master/graphcool.md#useful-graphcool-commands) for GraphQL in GraphCool using the GraphCool CLI

I have added some of the commands I use [and forget] for using the CLI if you find anything that is missing please feel free to submit a PR
