### ISSUE TITLE
graph.cool backend

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#6]
graph.cool schema needs creating

 - [ ] Understand the basics of GraphQL, currently building a [GraphQL getting started repo](https://github.com/spences10/graphql-getting-started)

**Comment by thomasmarr** [comment]
This page seems to be a starting point that gives you an example git repo to clone. Just thought it might be helpful. https://www.graph.cool/docs/quickstart/

**Comment by spences10** [comment]
Thanks, @GreatScot I have gone through some of them, and there really good :+1:
