### ISSUE TITLE
Set up staging with now

### ISSUE THREAD

**Issue by spences10** [chungu-voyage-bears-team-16/huddlehunt#9]
Have a staging area for the app to live for testing before it goes to prod

**Comment by spences10** [comment]
Links for the app, I couldn't really understand how this worked but think we should try for the team environment.

https://stage.now.sh/
https://github.com/zpnk/stage.now

**Comment by spences10** [comment]
After `slack`ing with one of the zeit team I understand that stage.now isn't part of zeit and is a community project. 

As such the support for this will be just that too, as it wasn't that clear on how to do this for a personal account doing it for a team or org was probably out of the scope of the project and so I don't think it will be of much use to us here.

What I suggest is we use `now` for deployments and share the deployed url for all to see

I have logged an issue with the stage.now project, I'll close this for now until we hear back of any new on using it, it the meantime I'll put documentation together on how to use `now`

@afixoftrix @GreatScot tagging you guys in for information, I'll have to come up with some documentation

**Comment by thomasmarr** [comment]
A little how-to would be helpful - but from googling it it seems like we just install a package, and then use a single command to deploy?
